name: shadow_game_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flame: ^1.21.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.11
  go_router: ^14.2.7
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  spritewidget: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/level_one/
    - assets/images/level_one/door/
    - assets/images/level_one/chest/
    - assets/images/shared/
    - assets/images/shared/damage/
    - assets/images/shared/endurance/
    - assets/images/shared/speed/
    - assets/images/shared/life/
    - assets/gifs/player/
    - assets/gifs/shadow/
    - assets/gifs/spider/
    - assets/gifs/
    - assets/images/sheets/player/
    - assets/images/sheets/shadow/
    - assets/images/sheets/spider/
    - assets/icons/
